# RuboCop v1.36.0

Metrics/MethodLength:
  Max: 20

Naming/MethodParameterName:
  Enabled: false # Don't need to deviate from math nomenclature

Naming/MethodName:
  Enabled: false # Don't need to spell out math variables
